"""Download the OFL-licensed web fonts used by the theme as woff2 files into assets/.

Fonts are self-hosted (not from Shopify's font library) so the storefront uses the
exact brand typefaces: Fraunces (display serif) + Inter (tracked sans), plus Arabic
faces for right-to-left pages and the invitation designs.

Usage: python3 tools/brand/fetch_fonts.py
"""
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ASSETS = ROOT / "assets"
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/124.0 Safari/537.36")

# (slug, css family name, google css2 family query, subsets to keep, snippet)
# snippet "fonts" = storefront, "fonts-invitation" = live invitation pages only.
FONTS = [
    ("fraunces", "Fraunces", "Fraunces:ital,opsz,wght@0,9..144,300..700;1,9..144,300..700", {"latin"}, "fonts"),
    ("inter", "Inter", "Inter:wght@300..700", {"latin"}, "fonts"),
    ("amiri", "Amiri", "Amiri:wght@400;700", {"arabic"}, "fonts"),
    ("plex-arabic", "IBM Plex Sans Arabic", "IBM+Plex+Sans+Arabic:wght@300;400;500;600", {"arabic"}, "fonts"),
    ("cormorant", "Cormorant Garamond", "Cormorant+Garamond:ital,wght@0,400;0,500;0,600;1,400", {"latin"}, "fonts-invitation"),
    ("pinyon", "Pinyon Script", "Pinyon+Script", {"latin"}, "fonts-invitation"),
    ("aref-ruqaa", "Aref Ruqaa", "Aref+Ruqaa:wght@400;700", {"arabic"}, "fonts-invitation"),
    ("reem-kufi", "Reem Kufi", "Reem+Kufi:wght@400..700", {"arabic"}, "fonts-invitation"),
    # Été design (from the "Summer Wedding" Canva design): closest OFL matches to its three typefaces
    ("arapey", "Arapey", "Arapey:ital@0;1", {"latin"}, "fonts-invitation"),
    ("bellefair", "Bellefair", "Bellefair", {"latin"}, "fonts-invitation"),
    ("muellerhoff", "Herr Von Muellerhoff", "Herr+Von+Muellerhoff", {"latin"}, "fonts-invitation"),
]
PRELOAD = {"font-fraunces-latin-normal-300-700.woff2", "font-inter-latin-normal-300-700.woff2"}


def get(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        data = r.read()
    return data if binary else data.decode("utf-8")


def main():
    manifest = []
    for slug, css_family, family, subsets, snippet in FONTS:
        css = get(f"https://fonts.googleapis.com/css2?family={family}&display=swap")
        blocks = re.findall(r"/\*\s*([\w-]+)\s*\*/\s*@font-face\s*{([^}]*)}", css)
        for subset, body in blocks:
            if subset not in subsets:
                continue
            style = re.search(r"font-style:\s*(\w+)", body).group(1)
            weight = re.search(r"font-weight:\s*([\d ]+);", body).group(1).strip()
            src = re.search(r"url\((https://[^)]+\.woff2)\)", body).group(1)
            urange = re.search(r"unicode-range:\s*([^;]+);", body).group(1).strip()
            wtag = weight.replace(" ", "-")
            name = f"font-{slug}-{subset}-{style}-{wtag}.woff2"
            (ASSETS / name).write_bytes(get(src, binary=True))
            manifest.append((css_family, name, style, weight, urange, snippet))
            print(f"{name:60s} {(ASSETS / name).stat().st_size/1024:7.1f} KB")
    write_snippets(manifest)
    return manifest


def write_snippets(manifest):
    for snippet in ("fonts", "fonts-invitation"):
        faces = [m for m in manifest if m[5] == snippet]
        lines = [
            "{%- comment -%}",
            "  Self-hosted OFL fonts — generated by tools/brand/fetch_fonts.py. Do not edit by hand.",
            "  unicode-range means Arabic files only download when Arabic text is on the page.",
            "{%- endcomment -%}",
        ]
        if snippet == "fonts":
            for _, name, *_ in faces:
                if name in PRELOAD:
                    lines.append(f"{{{{ '{name}' | asset_url | preload_tag: as: 'font', type: 'font/woff2', crossorigin: true }}}}")
        lines.append("{% style %}")
        for fam, name, style, weight, urange, _ in faces:
            lines.append(
                f"  @font-face {{ font-family: '{fam}'; font-style: {style}; font-weight: {weight}; "
                f"font-display: swap; src: url({{{{ '{name}' | asset_url }}}}) format('woff2'); unicode-range: {urange}; }}"
            )
        lines.append("{% endstyle %}")
        (ROOT / "snippets" / f"{snippet}.liquid").write_text("\n".join(lines) + "\n")
        print("wrote snippets/%s.liquid" % snippet)


if __name__ == "__main__":
    sys.exit(0 if main() else 1)
